name: flutter_discord_client
version: 1.0.1
description: Flutter Discord Client
homepage: https://github.com/phatdat-dev/flutter_discord_client.git

environment:
  sdk: ^3.10.4
  flutter: ">=3.38.5"

dependencies:
  dio: ^5.7.0
  equatable: ^2.0.7
  copy_with_extension: ^7.1.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_lints: any
  build_runner: any
  copy_with_extension_gen: ^7.1.0
  json_serializable: ^6.9.3
